check_plotting_packages <- function(){
  # check required packages exist
  if (!requireNamespace("dplyr", quietly = TRUE)) {
    stop("Package \"dplyr\" needed for this function to work. Please install it.",
         call. = FALSE)
  } else if (!requireNamespace("ggplot2", quietly = TRUE)) {
    stop("Package \"ggplot2\" needed for this function to work. Please install it.",
         call. = FALSE)
  } else if (!requireNamespace("ggpubr", quietly = TRUE)) {
    stop("Package \"ggpubr\" needed for this function to work. Please install it.",
         call. = FALSE)
  } else if (!requireNamespace("RColorBrewer", quietly = TRUE)) {
    stop("Package \"RColorBrewer\" needed for this function to work. Please install it.",
         call. = FALSE)
  } else if (!requireNamespace("tibble", quietly = TRUE)) {
    stop("Package \"tibble\" needed for this function to work. Please install it.",
         call. = FALSE)
  } else if (!requireNamespace("tidyr", quietly = TRUE)) {
    stop("Package \"tidyr\" needed for this function to work. Please install it.",
         call. = FALSE)
  }
}



#' plotRLE (ggplot edition)
#'
#' Make a RLE plot with specific group colourings
#'
#' @param exprs row matrix of gene expression (samples as rows)
#' @param group vector assigning columns of `exprs` to groups to colour by
#' @param pal (default = null), character vector of colours the length of
#'  the set of `group`. If left default this will be generated by using Set3
#'  which has a max n of 9
#'  @param title a title for the plot
#'
#' @return prints a RLE plot
#' @export
#'
#' @examples
plotGG_RLE_EDA <- function(exprs, group, pal = NULL, title = ""){
  check_plotting_packages()

  # replace any punctuation in group with whitespace
  group <- stringr::str_replace_all(group, "[[:punct:]]", " ") |>
    as.factor()

  ## set palette to Set1 if null
  if(is.null(pal)){
    pal <- RColorBrewer::brewer.pal(length(unique(group)), "Set1")
  }

  # generate RLE data: log(exprs) - geneWise median (colMed)
  exprs_rle <- log2(exprs + 1) - matrixStats::colMedians(log2(exprs + 1))

  exprs_rle_long <- exprs_rle |>
    as.data.frame() |>
    tibble::rownames_to_column(var = "sample") |>
    dplyr::mutate(group = group) |>
    tidyr::pivot_longer(-c(sample, group), names_to = "ensg", values_to = "rle")

  exprs_rle_long |>
    dplyr::arrange(group, sample) |>
    ggplot2::ggplot(ggplot2::aes(interaction(sample, group), rle, col = group)) +
    ggplot2::geom_boxplot(outlier.alpha = 0.1) +
    ggpubr::theme_pubr(
      border = TRUE,
      legend = "right"
    ) +
    ggplot2::theme(axis.text.x = ggplot2::element_blank(), axis.ticks.x = ggplot2::element_blank()) +
    ggplot2::scale_colour_manual(values = pal) +
    ggplot2::labs(
      title = title,
      x = NULL,
      y = NULL
    )
}


